### ISSUE TITLE
Question: TaskVehicle class

### ISSUE THREAD

**Issue by Kait0** [zhejz/carla-roach#1]
Hi,

I have a question about the class Task Vehicle in carla_gym\core\task_actor\common\task_vehicle.py

The init takes 4 arguments vehicle, target_transforms, spawn_transforms, endless.
I have a question about target_transforms and spawn_transforms.
What is the data structure that the waypoints are expected to be in?
Are the target_transforms supposed to be the route waypoints from the route.xml files?
Are the spawn_transforms meant to be the initial vehicle transform?
What coordinate system are they expected to be using, the same one as the .xml files?

**Comment by zhejz** [comment]
The TaskVehicle class is instantiate [here](https://github.com/zhejz/carla-roach/blob/3fce4093e58bf64c60094d2745257b5508975c7a/carla_gym/core/task_actor/ego_vehicle/ego_vehicle_handler.py#L54). 
`target_transforms` come from the `task_config`, which is defined by the loaded gym env, either loaded from xml files or randomly sampled.
`spawn_transforms` are randomly sampled, c.f. [here](https://github.com/zhejz/carla-roach/blob/3fce4093e58bf64c60094d2745257b5508975c7a/carla_gym/core/task_actor/ego_vehicle/ego_vehicle_handler.py#L25)
Both the target and the spawn transforms are in the CALAR global coordinate.

**Comment by Kait0** [comment]
Thank you.
