### ISSUE TITLE
Run benchmark with carla 0.9.13

### ISSUE THREAD

**Issue by ricokoff** [zhejz/carla-roach#11]
Hi,

I'm trying to run the carla-roach benchmark with carla 0.9.13. I am currently running into some segmentation faults when benchmarking the carla roaming agent. When using a max_step of 1 in the run_single function (benchmark.py), I only get a segmentation fault in benchmarks 'WetNoon_03' and 'SoftRainSunset_03'. However, when increasing the max_step to 5, it also occurs at many of the other benchmarks. The segmentation faults always occur while creating the zombiewalkers in the following loop (zombie_walker_handler.py):

```
        for w_id, c_id in zip(walker_ids, controller_ids):
            self.zombie_walkers[w_id] = ZombieWalker(w_id, c_id, self._world)
        return self.zombie_walkers
```

It completes some iterations, but after a while it gives the segmentation fault (Usually around 200/250). This code is run during the _zw_handler reset in carla_multi_agent_env.py. Does anyone know what could be the cause of these segmentation faults?

NOTE: I am using vehicle.audi.a2 instead of  vehicle.lincoln.mkz2017, because the lincoln doesn't seem to be recognized in carla 0.9.13.

**Comment by PDillis** [comment]
For what it's worth, the `vehicle.lincoln.mkz2017` has been renamed in CARLA 0.9.13 to `vehicle.lincoln.mkz_2017`.
