### ISSUE TITLE
Metric

### ISSUE THREAD

**Issue by neilsambhu** [zhejz/carla-roach#14]
In ego_vehicle_handler.py, is "score_route" "success rate"? I know "score_composed" is the "driving score".

**Comment by neilsambhu** [comment]
@zhejz, #14 is an unanswered question.

**Comment by zhejz** [comment]
"score_route" is the percentage of route completed, with respect to one route.
"score_composed" is computed by multiplying "score_route" with the "score_penalty", these metrics are used by the carla leaderboard.
"success_rate" is the percentage of routes that are fully completed, with respect to many routes. This metric is used by the nocrash benchmark.
You can find more details about the metrics in the paper and the website of the carla leaderboard.

**Comment by neilsambhu** [comment]
@zhejz, thank you for your response.
