### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by vaydingul** [zhejz/carla-roach#18]
Hi,

Currently, I am trying to train IL models from scratch. 
I am using a Tesla V100 (32GB) and 8 CPU cores to train models. Lastly, the batch size is 192. 
My dataset consists of 183000 data points collected with your dataset collection code.

At present, it takes approximately 3-4 hours to train one epoch. 
Was this the case for you? Can you let me know the GPU specs, training properties, and, finally, the epoch durations?
I would really appreciate it if you could help with this issue. 

Best.

**Comment by zhejz** [comment]
You can find more training details about the IL models in the appendix of the [arxiv version](https://arxiv.org/abs/2108.08265).
We use one 2080Ti GPU for the IL training. I can't remember how long each epoch takes, but I do remember after each DAGGER iteration it takes about one day to train a new IL model.

**Comment by vaydingul** [comment]
Thanks for the answer @zhejz .
