### ISSUE TITLE
Adding New Fields to the Dataset

### ISSUE THREAD

**Issue by vaydingul** [zhejz/carla-roach#20]
Hi,

As far as I understand, it is enough to change the observation configs to add new fields to the dataset. It is doable, for example, when I change the observation manager of an individual sensor _(i.e., ObsManager class of GNSS -- adding the sensor noise value to the observation dictionary for the sake of example --)_. However, when I run the default data collection code (i.e., data_collect_bc.sh), it does not add the `navigation.waypoint_plan` and `birdview.chauffeurnet` observation dictionaries to the dataset, which exists in the `agent/cilrs/obs_configs=central_rgb_wide.` Probably, I am missing the point here; that is, there are also other things that need to be set. At least, I would like to reach to `navigation.waypoint_plan` observation dictionary during the data acquisition. So, how can I add the observation dictionaries of other `ObsManager` modules to the dataset? I really appreciate it if you can help. 

Best.

**Comment by zhejz** [comment]
The `obs_configs` does not affect the data collection. To change what data is saved you can refer to [here](https://github.com/zhejz/carla-roach/blob/ba2fbfcdf39a0a7d460a6963a78bcc43ce42a85a/utils/saving_utils.py#L45). Just make sure what you want to save is a subset of what is observed as specified by the `obs_configs`.

**Comment by vaydingul** [comment]
Oh, great!
Thank you for the answer @zhejz . It certainly solved my problem.
