### ISSUE TITLE
Getting RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED while running  `train_rl.sh`

### ISSUE THREAD

**Issue by Z7MightGuy** [zhejz/carla-roach#21]
After I start running train_rl.sh, when the program executes this line `self.policy.forward(self._last_obs)` in `ppo.py`, the program gets stuck for a while and gives out the above error. @zhejz Do you have any idea?

**Comment by zhejz** [comment]
Hi, it should be related to cuDNN/cuda installation. Please double check your gpu is working and make sure you have installed the environment correctly.

**Comment by atg93** [comment]
Hi, 
I encountered the same problem. Downloading 

torch-1.12.0+cu113-cp38-cp38-linux_x86_64.whl
torchvision-0.13.0+cu113-cp38-cp38-linux_x86_64.whl

in https://download.pytorch.org/whl/cu113/torch/ solved the problem in my case.
