### ISSUE TITLE
Segmentation fault (core dumped) while training RL expert

### ISSUE THREAD

**Issue by atg93** [zhejz/carla-roach#22]
Hi,

First of all thank you very much for sharing your code and your work in the paper is very interesting. But I encounter a problem while training RL expert. I would appreciate if you help me.

I installed carla 0.9.10 like you said in Installation.md. I can run benchmark.py and observe the car's behavior in video log. However, when I run train_rl.py, it shows segmentation fault. Moreover,  I also noticed that the problem occurs when self._world tries to get vehicle_bbox_list and walker_bbox_list in chauffeurnet.py. 

Have you encountered similar problem while you train your RL expert ?

Thank you,

**Comment by zhejz** [comment]
No I didn't, but segmentation fault (core dumped) can be caused by many reasons and often it's CARLA related. For example, does your GPU has enough memory? train_rl.py runs pytorch training and multiple CARLA servers on a single GPU.

**Comment by atg93** [comment]
Thank you for your answer. I think this problem occurs when carla is installed by using pip. I re-created virtual environment and installed carla by using conda install in virtual environment. Then, the problem is solved.

**Comment by dsamvoel** [comment]
I have a same error. so, what version of carla did you install? and how did you install the carla by using conda install. When i installed the carla version of 0.9.10.1 by using conda install, it did not work
