### ISSUE TITLE
Setting the argument of n_episodes

### ISSUE THREAD

**Issue by yixiao1** [zhejz/carla-roach#3]
Hi,

Very impressive work! 
One simple question, when we set up the argument of `n_episodes`, if we need to take into account of the number of towns? For example, if I want to collect 1 episode per towns (Town 1, 3, 4, 6). Shall I set up the `n_episodes` to 1, or 4?

And for each episode, is the route (the start point and the end point) always set to the same?

Cheers,
Yi

**Comment by zhejz** [comment]
Hi, thanks for liking our work!
The `n_episodes` is the total episode collected, so in your example it should be set to 4 such that 1 episode will be collected for each town.
The start/end point depends on the gym_env specified. For benchmark envs (NoCrash, CoRL2017, Leaderboard), the start/end point is specified by the [xml file](https://github.com/zhejz/carla-roach/tree/main/carla_gym/envs/scenario_descriptions). For data collection and RL training there is an EndlessEnv, which has randomly selected start/end point.

**Comment by yixiao1** [comment]
Alright, I see. So I understand that the number is the amount of the total episodes among all towns. So if we set up the `n_episodes` to a number, let's say 60, this number will be automatically divided by 4, which means, 15 episodes per town.

Thanks a lot,
Yi
