### ISSUE TITLE
Would like some tips and advice to train big Reinforcement Learning agents like these

### ISSUE THREAD

**Issue by fcharity** [zhejz/carla-roach#34]
Thank you for your wonderful work! I am very much impressed with the consistency at which the RL training progresses and that must have required some phenomenal hyperparameter tuning and debugging skills. I would like to learn to tune hyperparamters for big and dynamic environments like these. I would appreciate it a lot if you could give me some suggestions and tips for hyperparameter tuning and debugging RL training process. Thank you once again! Cheers!

**Comment by zhejz** [comment]
Thanks! This is a really nice question. First of all, you can start with the famous "The Nuts and Bolts of Deep RL Research" by John Schulman ([link](http://joschu.net/docs/nuts-and-bolts.pdf)). Then personally I'd like to emphasize two things that matter a lot for our specific application autonomous driving: (1) Parallel simulation environment for accelerated experience collection. (2) Logging and visualizing everything you can think of such that later you can debug and reason.
