### ISSUE TITLE
how to change this line "from gym.wrappers.monitoring.video_recorder import ImageEncoder"

### ISSUE THREAD

**Issue by SExpert12** [zhejz/carla-roach#38]
CARLA version :0.9.14 in ubuntu.
Hi all, when I run the data_collect.py file, I am getting this error -
 "from gym.wrappers.monitoring.video_recorder import ImageEncoder
ImportError: cannot import name 'ImageEncoder' from 'gym.wrappers.monitoring.video_recorder"

When I search for error I got to know that ImageEncoder is deprecated. So how to change code for this line?

Thanks in advance.

**Comment by zhejz** [comment]
You could create an `ImageEncoder` locally and get rid of the dependency on openai_gym.
Please check out here: https://github.com/zhejz/TrafficBotsV1.5/blob/main/src/utils/video_recorder.py
