### ISSUE TITLE
 module 'tensorflow_estimator.python.estimator.api._v1.estimator' has no attribute 'distributions

### ISSUE THREAD

**Issue by HappyDay-design** [zhejz/carla-roach#4]
Hello
Hi. When I run the file train_rl.py there is an error that module 'tensorflow_estimator.python.estimator.api._v1.estimator' has no attribute 'distributions. I use tensorflow ==2.6.0. How to fix this error

**Comment by zhejz** [comment]
Hi, our code does not use tensorflow. It could be that your conda environment is not correctly set up.
