### ISSUE TITLE
Could not find run (wandb run error)

### ISSUE THREAD

**Issue by Shubhamcl** [zhejz/carla-roach#5]
Hi,

Has the run path been updated? 

I am trying to collect your dataset from the run path and it says:
Could not find run <Run zhejun/il_nocrash_ap/2pilkrol (not found)>

Or has it been unhosted?

**Comment by zhejz** [comment]
Hi,

the wandb run path `zhejun/il_nocrash_ap/2pilkrol` appears in [train_il.sh](https://github.com/zhejz/carla-roach/blob/ba2fbfcdf39a0a7d460a6963a78bcc43ce42a85a/run/train_il.sh#L28) which is used not for collecting dataset but for training IL agents after a dataset has been collected. 
Also `zhejun/il_nocrash_ap/2pilkrol` is an example wandb path, you should replace it with you own dataset.
For collecting datasets, please follow the "Collect Dataset" section in the readme.
