### ISSUE TITLE
ValueError: Could not find project

### ISSUE THREAD

**Issue by kejie7243** [zhejz/carla-roach#6]
Hello, I'm trying to run run/benchmark.sh and I need to modify agent.cilrs.rl_run_path and agent.cilrs.rl_ckpt_step such that I could load my ckpt. Sorry for a rookie in wandb, as shown in the official docs, agent.cilrs.rl_run_path should be in 'entity/project' format, while the entity is '' and project is 'il_leaderboard_roach' if I just follow the lb running in run/train_il.sh. But it keeps telling me that project is not found, any helps? Thanks!!

**Comment by zhejz** [comment]
Hi, the rl_run_path is in `entity/project/run_id` format, for example `iccv21-roach/trained-models/1929isj0`. You can copy the run path directly from wandb. It's in the [overview info page](https://wandb.ai/iccv21-roach/trained-models/runs/1929isj0/overview?workspace=user-) of a specific run.

**Comment by kejie7243** [comment]
Hello, thanks for replying! I'm asking how to load my own ckpt in the local after I run run/train_il.sh. I follow the default setting in train_il.sh and no entity name is set. Thanks!

**Comment by zhejz** [comment]
If no entity is set wandb will use the default entity, which is your wandb username. You can double check the run path of your checkpoint in the overview page of your wandb run.
