### ISSUE TITLE
Adding Leaderboard Scenarios

### ISSUE THREAD

**Issue by penghao-wu** [zhejz/carla-roach#8]
Hi, I wander have you tried to add the scenarios in Carla's scenario manager to your enviroment? I plan to do so but I am not sure whether py_trees used in the scenario manager supports multi-processing trainning (SubprocVecEnv). Thank you in advance!

**Comment by zhejz** [comment]
I spent some time trying to integrate the scenario_runner into the multi-processing RL training but it didn't work out smoothly. That's more than a year ago so I can't recall what problem exactly I've encountered. I remember my solution at that time was to write my own scenario_runner without using any dependencies (such as py_trees), but I didn't consider it as a priority.

**Comment by hli2020** [comment]
Just out of curiosity, are you planning to test on the Carla [sensor track ](https://leaderboard.carla.org/leaderboard/)leaderboard?

**Comment by zhejz** [comment]
> Just out of curiosity, are you planning to test on the Carla [sensor track ](https://leaderboard.carla.org/leaderboard/)leaderboard?

No, for that a scenario_runner has to be implemented or integrated, then all models have to be trained with those scenarios. 
Besides, to obtain a good ranking on the online leaderboard it is inevitable to spend time overfitting the secret testing env, which, in my opinion, does not add too much value.

**Comment by Kin-Zhang** [comment]
> Hi, I wander have you tried to add the scenarios in Carla's scenario manager to your enviroment? I plan to do so but I am not sure whether py_trees used in the scenario manager supports multi-processing trainning (SubprocVecEnv). Thank you in advance!

I also want to run this Roach agent to see whether it can run at `scenario manager` the official branch leaderboard from carla, but it seems hard to extract the author's agent. lol
